// Generated by https://quicktype.io

export interface CreateTokenCard {
  card_number: number;
  email: string;
  expiration_month: string;
  expiration_year: string;
  token: string;
  exp: number;
  _id: string;
  __v: number;
}
